# Generated by Django 5.0.2 on 2024-03-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiveReApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='404-image.jpg', upload_to='mod_images/'),
        ),
    ]
