# Generated by Django 5.0.2 on 2024-03-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiveReApp', '0003_remove_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
