# Generated by Django 5.0.2 on 2024-03-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiveReApp', '0005_alter_question_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, default='/question_image/下载.jpg', null=True, upload_to='question_image/', verbose_name='封面图'),
        ),
    ]
