# Generated by Django 5.0.2 on 2024-03-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiveReApp', '0007_alter_choice_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='value',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.CharField(default='some_default_value', max_length=255),
        ),
    ]
