# Generated by Django 5.0.2 on 2024-03-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiveReApp', '0008_remove_rating_value_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
