# Generated by Django 5.0.2 on 2024-03-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moiveReApp', '0009_rating_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
