# Generated by Django 5.0.2 on 2024-03-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiveReApp', '0010_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='detail',
            field=models.CharField(default='None', max_length=600),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='moiveReApp.tag'),
        ),
    ]
