# Generated by Django 5.0.2 on 2024-03-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiveReApp', '0011_tag_question_detail_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='img_url',
            field=models.URLField(blank=True, null=True, verbose_name='外部图片链接'),
        ),
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.CharField(default='http://127.0.0.1:8000/moiveReApp/', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=models.CharField(default=' ', max_length=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, default='question_image/placeholder.jpg', null=True, upload_to='question_image/', verbose_name='封面图'),
        ),
    ]
